version: '2'

services:
  nodebackend:
    image: node:11
    ports:
      - 4000:4000
    working_dir: /node
    volumes:
      - ./node:/node
      - /node/node_modules
      - ./node/ingredients:/node/ingredients
    depends_on:
      - postgresdb
    command: bash -c "yarn && yarn dev"

  postgresdb:
    image: postgres
    volumes: 
      - ./postgres:/var/lib/postgresql/tasteIT
    ports:
      - 5000:5432
    ##environment:
     ## POSTGRES_PASSWORD: yeet
     ## POSTGRES_DB: tasteit

    ##name: postgresdb
    
